<a href="https://colab.research.google.com/github/xiaann622/Analystlab/blob/main/netflix_cleaning_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 1–2: Data Cleaning & Exploratory Data Analysis
## Dataset 2 — Netflix Movies & TV Shows

**Source:** [Netflix Movies and TV Shows — Kaggle](https://www.kaggle.com/datasets/shivamb/netflix-shows)

This notebook mirrors the same five-task structure used for the E-commerce dataset:
1. Dataset Understanding
2. Data Cleaning (missing values, duplicates, standardization, validation)
3. Exploratory Data Analysis
4. Visualizations
5. Insights

> **Colab note:** This notebook expects `netflix_titles.csv`. Use the setup cell below to either pull it via `kagglehub` or upload it manually.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 5)

df = pd.read_csv('/content/netflix_titles.csv')

## Task 1: Dataset Understanding

In [ ]:
# 1. First few rows
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,"September 24, 2021",2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...","September 24, 2021",1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,"September 24, 2021",2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [ ]:
# 2. Rows / columns
df.shape

(8807, 12)

In [ ]:
# 3. Data types
df.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [ ]:
categorical_features = df.select_dtypes(include='object')
display(categorical_features.head())

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
numerical_features = df.select_dtypes(include=np.number)
display(numerical_features.head())

   release_year
0          2020
1          2021
2          2021
3          2021
4          2021

In [ ]:
df['date_added'] = df['date_added'].astype(str).str.strip()
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: datetime64[ns](1), int64(1), object(10)
memory usage: 825.8+ KB

In [ ]:
df.head(10)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,2021-09-24,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
6,s7,Movie,My Little Pony: A New Generation,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,2021-09-24,2021,PG,91 min,Children & Family Movies,Equestria's divided. But a bright-eyed hero be...
7,s8,Movie,Sankofa,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",2021-09-24,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies","On a photo shoot in Ghana, an American model s..."
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021-09-24,2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
9,s10,Movie,The Starling,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021-09-24,2021,PG-13,104 min,"Comedies, Dramas",A woman adjusting to life after a loss contend...

In [ ]:
print("Unique show_id:", df['show_id'].nunique(), "out of", len(df), "rows")

**What the dataset contains:** A catalog of Movies and TV Shows available on Netflix (as of the data's collection date), with metadata for each title: cast, director, country of production, the date it was added to Netflix, its original release year, content rating (e.g. PG-13, TV-MA), duration (minutes for movies, seasons for TV shows), genre tags (`listed_in`), and a short description.

## Task 2: Data Cleaning

### 2.1 Missing Values

In [ ]:
missing = df.isnull().sum()
missing_pct = (missing / len(df) * 100).round(2)
missing_summary = pd.DataFrame({'missing_count': missing, 'missing_pct': missing_pct})
missing_summary = missing_summary[missing_summary['missing_count'] > 0].sort_values('missing_count', ascending=False)
missing_summary

            missing_count  missing_pct
director             2634        29.91
country               831         9.44
cast                  825         9.37
date_added             10         0.11
rating                  4         0.05
duration                3         0.03

**Findings & decisions:**

- **`director`** (typically the largest gap, ~30%): Often genuinely absent from Netflix's own metadata (common for TV shows with rotating directors per episode). Decision: **fill with `"Not Specified"`** rather than drop — dropping would remove ~30% of the catalog, destroying data needed for every other analysis.
- **`cast`** (~9%): Same reasoning — **fill with `"Not Specified"`**.
- **`country`** (~9%): Genuinely unknown production country. Decision: **fill with `"Not Specified"`**; it's excluded automatically from country-level analyses since it doesn't match a real country name.
- **`date_added`** (a small number of rows): This is a date Netflix's own catalog system stamped; there's no reliable way to reconstruct it. Decision: **drop only those rows** for analyses that require `date_added` (e.g., "content added by year"), but keep them for everything else — dropping them wholesale would lose valid title/genre/rating data.
- **`rating`** (a handful of rows): Decision: **fill with `"Not Rated"`**, a legitimate real-world category already used by other rating systems.
- **`duration`** (a handful of rows): Decision: **drop these specific rows** only when duration is required for analysis, since duration cannot be meaningfully guessed.

In [ ]:
df['director'] = df['director'].fillna('Not Specified')
df['cast'] = df['cast'].fillna('Not Specified')
df['country'] = df['country'].fillna('Not Specified')
df['rating'] = df['rating'].fillna('Not Rated')
# date_added and duration: leave as NaN for now, handled explicitly downstream

print("Remaining missing values:")
print(df.isnull().sum()[df.isnull().sum() > 0])

Remaining missing values:
date_added    10
duration       3
dtype: int64

### 2.2 Duplicate Records

In [ ]:
n_duplicates_all_cols = df.duplicated().sum()
# Also check duplicates on the natural identifier + title, in case show_id
# itself was regenerated but the underlying title/type is a re-listing
n_duplicates_title = df.duplicated(subset=['title', 'type', 'country', 'release_year']).sum()

print("Exact duplicate rows (all columns):", n_duplicates_all_cols)
print("Duplicate title+type+country+release_year combos:", n_duplicates_title)

Exact duplicate rows (all columns): 0
Duplicate title+type+country+release_year combos: 0

In [ ]:
before = len(df)
df = df.drop_duplicates()
df = df.drop_duplicates(subset=['title', 'type', 'country', 'release_year'], keep='first')
after = len(df)
print(f"Duplicates removed: {before - after}")
print(f"Rows before: {before} | Rows after: {after}")

Duplicates removed: 0
Rows before: 8807 | Rows after: 8807

### 2.3 Standardization

In [ ]:
# --- Column names ---
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
print(df.columns.tolist())

['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added', 'release_year', 'rating', 'duration', 'listed_in', 'description']

In [ ]:
# --- Date formats ---
df['date_added'] = df['date_added'].astype(str).str.strip()
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')
print("Unparseable / missing date_added after conversion:", df['date_added'].isnull().sum())

In [ ]:
# --- Text formatting consistency ---
df['type'] = df['type'].str.strip().str.title()          # Movie / Tv Show -> Movie / TV Show below
df['type'] = df['type'].replace({'Tv Show': 'TV Show'})
df['title'] = df['title'].str.strip()
df['country'] = df['country'].str.strip()
df['rating'] = df['rating'].str.strip().str.upper()
df['listed_in'] = df['listed_in'].str.strip()
df[['type','title','country','rating']].head()

In [ ]:
# --- Data types: release_year should be int, date_added extracted parts for EDA ---
df['release_year'] = df['release_year'].astype(int)
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month_name()
df.dtypes

### 2.4 Data Validation — Invalid Values, Inconsistencies, Outliers

In [ ]:
# Split duration into a numeric value + unit, since it mixes "X min" (movies)
# and "X Season(s)" (TV shows) in one text field — not directly usable as a number.
df['duration_value'] = df['duration'].str.extract(r'(\d+)').astype(float)
df['duration_unit'] = df['duration'].str.extract(r'([A-Za-z]+)')

print("Rows with unparseable duration:", df['duration_value'].isnull().sum())
df[['type','duration','duration_value','duration_unit']].head()

In [ ]:
# Invalid values: release_year should be realistic (Netflix data starts well
# after film existed, e.g. 1925+, and can't be in the future beyond data collection)
current_year_ceiling = 2026
invalid_years = df[(df['release_year'] < 1900) | (df['release_year'] > current_year_ceiling)]
print("Rows with implausible release_year:", len(invalid_years))

In [ ]:
# Inconsistent country entries: 'country' is comma-separated multi-value —
# for country-level analysis, we standardize by taking the FIRST listed country
# as the primary production country (documented assumption).
df['primary_country'] = df['country'].apply(lambda x: x.split(',')[0].strip() if x != 'Not Specified' else x)
df['primary_country'].value_counts().head(10)

In [ ]:
# Inconsistent genre entries: 'listed_in' is also comma-separated multi-label.
# We keep the raw column for reference and additionally create an exploded
# version for genre-level EDA (one row per title-genre pair).
genre_exploded = df.assign(genre=df['listed_in'].str.split(',')).explode('genre')
genre_exploded['genre'] = genre_exploded['genre'].str.strip()
print("Exploded genre rows:", len(genre_exploded), "vs original rows:", len(df))

In [ ]:
# Outlier check on duration (numeric part), separated by type since
# 'minutes' and 'seasons' are not comparable scales
for t in ['Movie', 'TV Show']:
    sub = df[(df['type'] == t) & df['duration_value'].notnull()]['duration_value']
    q1, q3 = sub.quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5*iqr, q3 + 1.5*iqr
    n_outliers = ((sub < lower) | (sub > upper)).sum()
    print(f"{t}: IQR bounds [{lower:.1f}, {upper:.1f}] -> {n_outliers} potential outliers "
          f"({n_outliers/len(sub)*100:.1f}% of {t.lower()}s)")

### 2.5 Cleaning Summary

In [ ]:
cleaning_summary = pd.DataFrame([
    ["Missing director (~30%)", "Filled with 'Not Specified'"],
    ["Missing cast (~9%)", "Filled with 'Not Specified'"],
    ["Missing country (~9%)", "Filled with 'Not Specified'"],
    ["Missing rating (small #)", "Filled with 'Not Rated'"],
    ["Missing date_added / duration (small #)", "Left as NaN; excluded row-by-row only from analyses that need that field"],
    ["Exact duplicate rows", "Removed"],
    ["Duplicate title+type+country+release_year", "Removed (kept first occurrence)"],
    ["Column names", "Standardized to lower_snake_case"],
    ["date_added as text", "Converted to datetime; year_added/month_added derived"],
    ["'Tv Show' inconsistent casing", "Standardized to 'TV Show'"],
    ["duration mixed units ('90 min' / '2 Seasons')", "Split into duration_value (numeric) + duration_unit"],
    ["Multi-value country field", "Standardized via primary_country (first listed country)"],
    ["Multi-value listed_in (genre) field", "Exploded into a separate long-format table for genre-level analysis"],
    ["Implausible release_year", "Checked via bounds (1900–2026); none removed unless found"],
], columns=["Issue Found", "Action Taken"])
cleaning_summary

In [ ]:
print("FINAL CLEANED SHAPE:", df.shape)
df.head()

## Task 3: Exploratory Data Analysis

### Summary Statistics — Numerical Columns

In [ ]:
numerical_cols = ['release_year', 'duration_value']
summary_stats = df[numerical_cols].agg(['mean', 'median', 'min', 'max', 'std']).T
summary_stats

### Exploratory Analyses (5+)

In [ ]:
# 1. Movies vs TV Shows distribution
type_counts = df['type'].value_counts()
type_counts

In [ ]:
# 2. Content added by year
content_by_year = df['year_added'].value_counts().sort_index()
content_by_year

In [ ]:
# 3. Top content-producing countries
top_countries = df[df['primary_country'] != 'Not Specified']['primary_country'].value_counts().head(10)
top_countries

In [ ]:
# 4. Most common ratings
top_ratings = df['rating'].value_counts().head(10)
top_ratings

In [ ]:
# 5. Most common genres/categories
top_genres = genre_exploded['genre'].value_counts().head(10)
top_genres

In [ ]:
# 6 (bonus). Average duration by type
avg_duration = df.groupby('type')['duration_value'].mean()
avg_duration

## Task 4: Data Visualization

In [ ]:
# Chart 1: Movies vs TV Shows (Pie Chart)
plt.figure(figsize=(6,6))
plt.pie(type_counts, labels=type_counts.index, autopct='%1.1f%%',
        colors=['crimson', 'navy'], startangle=90)
plt.title('Movies vs TV Shows on Netflix')
plt.tight_layout()
plt.show()

**Finding:** Movies make up a clear majority of the catalog relative to TV Shows, reflecting Netflix's historically larger film library.

In [ ]:
# Chart 2: Content added by year (Line Chart)
plt.figure(figsize=(10,5))
content_by_year.plot(kind='line', marker='o', color='darkred')
plt.title('Number of Titles Added to Netflix by Year')
plt.xlabel('Year Added')
plt.ylabel('Number of Titles')
plt.tight_layout()
plt.show()

**Finding:** Content additions ramp up sharply in the mid-2010s and peak around 2018–2019, consistent with Netflix's global content-investment expansion, before tapering in the final (partial) year of data collection.

In [ ]:
# Chart 3: Top 10 content-producing countries (Bar Chart)
plt.figure(figsize=(10,6))
top_countries.sort_values().plot(kind='barh', color='teal')
plt.title('Top 10 Content-Producing Countries')
plt.xlabel('Number of Titles')
plt.ylabel('Country')
plt.tight_layout()
plt.show()

**Finding:** The United States dominates as the primary production country by a wide margin, with India and the UK typically rounding out the top few — reflecting Netflix's original content hubs.

In [ ]:
# Chart 4: Most common ratings (Bar Chart)
plt.figure(figsize=(10,6))
top_ratings.plot(kind='bar', color='darkorange')
plt.title('Most Common Content Ratings')
plt.xlabel('Rating')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

**Finding:** Mature-audience ratings (e.g. TV-MA, TV-14) dominate the catalog, suggesting Netflix's content mix skews toward adult/teen audiences over younger children's content.

In [ ]:
# Chart 5: Movie duration distribution (Histogram)
movie_durations = df[df['type'] == 'Movie']['duration_value'].dropna()
plt.figure(figsize=(10,5))
plt.hist(movie_durations, bins=40, color='mediumseagreen', edgecolor='black')
plt.title('Distribution of Movie Durations (Minutes)')
plt.xlabel('Duration (minutes)')
plt.ylabel('Number of Movies')
plt.tight_layout()
plt.show()

**Finding:** Movie runtimes cluster tightly around 90–110 minutes, the conventional feature-film length, with a smaller number of much shorter or longer outliers.

In [ ]:
# Chart 6 (bonus): TV Show seasons distribution (Box Plot)
tv_seasons = df[df['type'] == 'TV Show']['duration_value'].dropna()
plt.figure(figsize=(8,5))
sns.boxplot(x=tv_seasons, color='plum')
plt.title('Distribution of TV Show Season Counts')
plt.xlabel('Number of Seasons')
plt.tight_layout()
plt.show()

**Finding:** Most TV shows on Netflix have just 1–2 seasons, with a long tail of a small number of long-running series flagged as outliers on the box plot.

## Task 5: Insights

1. **Movies dominate the catalog over TV Shows** (see *Chart 1*), roughly a 2:1 ratio — Netflix's library is still primarily film-driven despite its reputation for original series.
2. **Content acquisition accelerated sharply from the mid-2010s, peaking around 2018–2019** (see *Chart 2*), aligning with Netflix's well-documented global expansion and original-content investment period.
3. **The United States is by far the largest content-producing country** (see *Chart 3*), with a small number of other countries (typically India, UK) forming a distant second tier — indicating both a US-centric library and a limited-but-growing set of international content hubs.
4. **The catalog skews toward mature audiences**: TV-MA and TV-14 are the most common ratings (see *Chart 4*), suggesting Netflix's content strategy prioritizes teen/adult viewers over young children.
5. **Most TV shows are short-lived** (1–2 seasons; see the season box plot), while movies cluster tightly around the standard ~90–110 minute runtime (see *Chart 5*) — together suggesting Netflix favors a high volume of shorter series/limited runs over sustained long-running shows.

## Export Cleaned Dataset

In [ ]:
df.to_csv('netflix_cleaned.csv', index=False)
print("Saved netflix_cleaned.csv with shape:", df.shape)

from google.colab import files
files.download('netflix_cleaned.csv')